import { Resend } from 'resend';
import { logger } from '../utils/logger';

const resend = new Resend(process.env.RESEND_API_KEY!);

export async function sendWeeklyDigestEmail(params: {
  weekLabel: string;
  weekSummary: string;
  monthSummary: string;
  insights: string;
  date: string;
}) {
  const { weekLabel, weekSummary, monthSummary, insights, date } = params;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; color: #1e293b; margin: 0; padding: 0; }
  .container { max-width: 640px; margin: 32px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .header { background: #0f172a; color: #fff; padding: 32px; }
  .header h1 { margin: 0 0 4px; font-size: 22px; }
  .header p { margin: 0; color: #94a3b8; font-size: 14px; }
  .section { padding: 24px 32px; border-bottom: 1px solid #f1f5f9; }
  .section h2 { margin: 0 0 12px; font-size: 16px; color: #0f172a; text-transform: uppercase; letter-spacing: 0.05em; }
  .section pre { white-space: pre-wrap; font-family: inherit; margin: 0; line-height: 1.6; }
  .footer { padding: 20px 32px; text-align: center; font-size: 12px; color: #94a3b8; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Weekly AI Digest</h1>
    <p>${weekLabel}</p>
  </div>
  <div class="section">
    <h2>This Week</h2>
    <pre>${weekSummary || 'No conversations this week.'}</pre>
  </div>
  <div class="section">
    <h2>Monthly Themes</h2>
    <pre>${monthSummary || 'No monthly summary yet.'}</pre>
  </div>
  <div class="section">
    <h2>AI Insights &amp; Ideas</h2>
    <pre>${insights}</pre>
  </div>
  <div class="footer">Generated by holop.dev · ${date}</div>
</div>
</body>
</html>`;

  const result = await resend.emails.send({
    from: process.env.EMAIL_FROM ?? 'shoyu@holop.dev',
    to: process.env.EMAIL_TO!,
    subject: `Weekly AI Digest — ${weekLabel}`,
    html,
  });

  logger.info('Weekly digest email sent', result);
  return result;
}
